server {
    listen 80;
    server_name localhost;
    merge_slashes off;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /firebase_storage/ {
        resolver 8.8.8.8 valid=30s;

        set $firebase_path $request_uri;
        if ($firebase_path ~ ^/firebase_storage(.+)$) {
            set $firebase_path $1;
        }

        proxy_pass https://firebasestorage.googleapis.com$firebase_path;

        proxy_ssl_server_name on;
        proxy_ssl_protocols TLSv1.2 TLSv1.3;

        proxy_set_header Host firebasestorage.googleapis.com;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_set_header Origin "";
        proxy_set_header Referer "";

        proxy_hide_header Access-Control-Allow-Origin;

        add_header Access-Control-Allow-Origin * always;
        add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
        add_header Access-Control-Allow-Headers "Authorization,Content-Type,Accept,Origin" always;

        if ($request_method = OPTIONS) {
            return 204;
        }
    }
}