// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu9O-GUZp4_k2_O5pXstyfRewM1waFsMI',
    appId: '1:513445707596:web:d2dfb4ce0af21f277719e9',
    messagingSenderId: '513445707596',
    projectId: 'photo-app-72886',
    authDomain: 'photo-app-72886.firebaseapp.com',
    storageBucket: 'photo-app-72886.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi7RFzyZiLtvurHDQPRAAvk_DUBHQeXAg',
    appId: '1:513445707596:android:253cae22c8738cb77719e9',
    messagingSenderId: '513445707596',
    projectId: 'photo-app-72886',
    storageBucket: 'photo-app-72886.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQIotbbuj4yjtRH8xkWly4wq7egEpIZKk',
    appId: '1:513445707596:ios:431dbb0c1a1857be7719e9',
    messagingSenderId: '513445707596',
    projectId: 'photo-app-72886',
    storageBucket: 'photo-app-72886.firebasestorage.app',
    iosClientId: '513445707596-7vbo075qe7ukrg9mr8gpaj5pqe9ipnia.apps.googleusercontent.com',
    iosBundleId: 'hr.algebra.factApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQIotbbuj4yjtRH8xkWly4wq7egEpIZKk',
    appId: '1:513445707596:ios:431dbb0c1a1857be7719e9',
    messagingSenderId: '513445707596',
    projectId: 'photo-app-72886',
    storageBucket: 'photo-app-72886.firebasestorage.app',
    iosClientId: '513445707596-7vbo075qe7ukrg9mr8gpaj5pqe9ipnia.apps.googleusercontent.com',
    iosBundleId: 'hr.algebra.factApp',
  );
}
